// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8uZuxrpt0osLxVS4dCtXwYHqLf9mJ2D0',
    appId: '1:1018982776876:web:8579d7d26533f8522fd189',
    messagingSenderId: '1018982776876',
    projectId: 'fumiclick-a49a2',
    authDomain: 'fumiclick-a49a2.firebaseapp.com',
    storageBucket: 'fumiclick-a49a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfNtyv5Ho3zZBfca3dxm7CwoOmBRmcBRU',
    appId: '1:1018982776876:android:f3a1f9cb48b7f8d12fd189',
    messagingSenderId: '1018982776876',
    projectId: 'fumiclick-a49a2',
    storageBucket: 'fumiclick-a49a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqD3aie29sdyp3SurPakA_Muw4tbLPrIY',
    appId: '1:1018982776876:ios:0ae7ca7dde5336402fd189',
    messagingSenderId: '1018982776876',
    projectId: 'fumiclick-a49a2',
    storageBucket: 'fumiclick-a49a2.firebasestorage.app',
    iosBundleId: 'com.example.fumiClick',
  );

}